postgres:
	docker run --name postgres --network bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:17-alpine


createdb:
		docker exec -it postgres17 /bin/sh createdb --username=root --owner=root simple_bank 

dropdb:
		docker exec -it postgres17 /bin/sh dropdb simple_bank

migrateup:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank up

migrateup1:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank up 1

migratedown:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank down

migratedown1:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank down 1

sqlc:
	sqlc generate

test:
	go test -v -cover ./...

server:
		go run main.go
mock:
	mockgen -package mockdb -destination db/mock/store.go github.com/nuggetplum/simplebank/db/sqlc Store


.PHONY:createdb dropdb migrateup migratedown