postgres:
	docker run --name postgres --network bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:17-alpine


createdb:
		docker exec -it postgres17 /bin/sh createdb --username=root --owner=root simple_bank 

goose create:
		goose create  name sql

dropdb:
		docker exec -it postgres17 /bin/sh dropdb simple_bank

migrateup:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank up

migrateup1:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank up 1

migratedown:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank down

migratedown1:
		goose postgres postgresql://root:secret@localhost:5432/simple_bank down 1

sqlc:
	sqlc generate

test:
	go test -v -cover ./...

server:
		go run main.go
mock:
	mockgen -package mockdb -destination db/mock/store.go github.com/nuggetplum/simplebank/db/sqlc Store

docker simplebank:
	docker run --name simplebank -p 8080:8080 simplebank:latest
	docker run --name simplebank -p 8080:8080 -e GIN_MODE=release simplebank:latest
	docker run --name simplebank -p 8080:8080 -e GIN_MODE=release -e DB_SOURCE="postgresql://root:secret@172.17.0.3:5432/simple_bank?sslmode=disable" simplebank:latest
	docker run --name simplebank --network bank-network  -p 8080:8080 -e GIN_MODE=release -e DB_SOURCE="postgresql://root:secret@postgres17:5432/simple_bank?sslmode=disable" simplebank:latest

db_docs:
	dbdocs build doc/db.dbml

db_schema:
	dbml2sql --postgres -o doc/schema.sql doc/db.dbml

proto:
	rm -f pb/*.go
	protoc --proto_path=proto --go_out=pb --go_opt=paths=source_relative \
	--go-grpc_out=pb --go-grpc_opt=paths=source_relative \
	--grpc-gateway_out=pb --grpc-gateway_opt=paths=source_relative \
	proto/*.proto

evans:
	evans --host localhost --port 9090 -r repl

.PHONY:createdb dropdb migrateup migratedown proto